import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";

const font = Ubuntu({ weight: "300", subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
